language: go

go:
  - 1.6

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint

script:
  - "[[ $(go fmt ./... | wc -l) -le 0 ]]"
  - go vet ./...
  - golint ./...
  - go test -v -race -bench . -benchmem ./...
  - bin/coverage
