---
# Copyright (c) 2016-2017 Christian Saide <supernomad>
# Licensed under the MPL-2.0, for details see https://github.com/supernomad/quantum/blob/master/LICENSE

version: "2.1"
services:
  quantum0:
    cpuset: "2,3"
    container_name: quantum0
    build:
      context: "./dist/docker"
    restart: unless-stopped
    extra_hosts:
      - "etcd.quantum.dev:172.19.0.4"
      - "etcd.quantum.dev:fd00:dead:beef::4"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - $GOPATH/bin/quantum:/bin/quantum
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/certs/:/etc/quantum/ssl/certs/:ro
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/keys/:/etc/quantum/ssl/keys/:ro
      - quantum0:/var/lib/quantum/
    networks:
      local:
        ipv4_address: 172.19.0.2
        ipv6_address: fd00:dead:beef::2
    entrypoint:
      - "/bin/start_quantum.sh"
      - "masquerade"
      - "--datastore-endpoints"
      - "etcd.quantum.dev:2379"
      - "--private-ip"
      - "10.99.0.1"
      - "--datastore-tls-cert"
      - "/etc/quantum/ssl/certs/quantum0.quantum.dev.crt"
      - "--datastore-tls-key"
      - "/etc/quantum/ssl/keys/quantum0.quantum.dev.key"
      - "--datastore-tls-ca-cert"
      - "/etc/quantum/ssl/certs/ca.crt"
      - "--dtls-cert"
      - "/etc/quantum/ssl/certs/ec-server.crt"
      - "--dtls-key"
      - "/etc/quantum/ssl/keys/ec-server.key"
      - "--dtls-ca-cert"
      - "/etc/quantum/ssl/certs/ec-ca.crt"
      - "--plugins"
      - "compression,encryption"
      - "--floating-ips"
      - "10.99.2.1"
  quantum1:
    cpuset: "0,1,2"
    container_name: quantum1
    build:
      context: "./dist/docker"
    restart: unless-stopped
    extra_hosts:
      - "etcd.quantum.dev:172.19.0.4"
      - "etcd.quantum.dev:fd00:dead:beef::4"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - $GOPATH/bin/quantum:/bin/quantum
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/certs/:/etc/quantum/ssl/certs/:ro
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/keys/:/etc/quantum/ssl/keys/:ro
      - quantum1:/var/lib/quantum/
    environment:
      QUANTUM_UNENCRYPTED: "true"
      QUANTUM_TRUSTED: "10.99.2.1/32,10.99.2.2"
      QUANTUM_PUBLIC_IP: "172.19.0.3"
      QUANTUM_DATASTORE_ENDPOINTS: "etcd.quantum.dev:2379"
      QUANTUM_DATASTORE_TLS_CA_CERT: "/etc/quantum/ssl/certs/ca.crt"
      QUANTUM_DATASTORE_TLS_CERT: "/etc/quantum/ssl/certs/quantum1.quantum.dev.crt"
      QUANTUM_DATASTORE_TLS_KEY: "/etc/quantum/ssl/keys/quantum1.quantum.dev.key"
      QUANTUM_DTLS_CA_CERT: "/etc/quantum/ssl/certs/ec-ca.crt"
      QUANTUM_DTLS_CERT: "/etc/quantum/ssl/certs/ec-server.crt"
      QUANTUM_DTLS_KEY: "/etc/quantum/ssl/keys/ec-server.key"
      QUANTUM_PLUGINS: "compression"
      QUANTUM_FLOATING_IPS: "10.99.2.1"
    networks:
      local:
        ipv4_address: 172.19.0.3
        ipv6_address: fd00:dead:beef::3
    entrypoint: ["/bin/start_quantum.sh"]
  quantum2:
    cpuset: "1"
    container_name: quantum2
    build:
      context: "./dist/docker"
    restart: unless-stopped
    extra_hosts:
      - "etcd.quantum.dev:172.19.0.4"
      - "etcd.quantum.dev:fd00:dead:beef::4"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - $GOPATH/bin/quantum:/bin/quantum
      - $GOPATH/src/github.com/supernomad/quantum/dist/docker/quantum.yml:/etc/quantum/quantum.yml:ro
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/certs/:/etc/quantum/ssl/certs/:ro
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/keys/:/etc/quantum/ssl/keys/:ro
      - quantum2:/var/lib/quantum/
    environment:
      QUANTUM_CONF_FILE: "/etc/quantum/quantum.yml"
    networks:
      local:
        ipv4_address: 172.19.0.5
        ipv6_address: fd00:dead:beef::5
    entrypoint: ["/bin/start_quantum.sh"]
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd
    extra_hosts:
      - "etcd.quantum.dev:172.19.0.4"
      - "etcd.quantum.dev:fd00:dead:beef::4"
    volumes:
      - etcd:/var/lib/etcd
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/certs/:/etc/etcd/ssl/certs/:ro
      - $GOPATH/src/github.com/supernomad/quantum/dist/ssl/keys/:/etc/etcd/ssl/keys/:ro
    ports:
      - 2379:2379
    networks:
      local:
        ipv4_address: 172.19.0.4
        ipv6_address: fd00:dead:beef::4
    environment:
      ETCD_LISTEN_CLIENT_URLS: "https://[fd00:dead:beef::4]:2379, https://172.19.0.4:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "https://[fd00:dead:beef::4]:2379, https://172.19.0.4:2379"
      ETCD_CERT_FILE: "/etc/etcd/ssl/certs/etcd.quantum.dev.crt"
      ETCD_KEY_FILE: "/etc/etcd/ssl/keys/etcd.quantum.dev.key"
      ETCD_TRUSTED_CA_FILE: "/etc/etcd/ssl/certs/ca.crt"
      ETCD_DATA_DIR: "/var/lib/etcd"
      ETCD_NAME: "datastore"
    entrypoint: ["/usr/local/bin/etcd", "--client-cert-auth=true"]
networks:
  local:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: '172.19.0.0/24'
          gateway: '172.19.0.1'
        - subnet: 'fd00:dead:beef::/64'
          gateway: 'fd00:dead:beef::1'
volumes:
  etcd:
    driver: local
  quantum0:
    driver: local
  quantum1:
    driver: local
  quantum2:
    driver: local
