version: "2"
services:
  quantum0:
    container_name: quantum0
    build:
      context: "."
    extra_hosts:
      - "etcd.quantum.dev:172.18.0.4"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - $GOPATH/bin/quantum:/bin/quantum
      - ./certs/:/etc/quantum/certs/:ro
      - quantum0:/var/lib/quantum
    networks:
      perf_net:
        ipv4_address: 172.18.0.2
    entrypoint: ["/bin/quantum", "-endpoints", "etcd.quantum.dev:2379", "-public-ip", "172.18.0.2", "--tls-cert", "/etc/quantum/certs/quantum0.quantum.dev.crt", "--tls-key", "/etc/quantum/certs/quantum0.quantum.dev.key", "--tls-ca-cert", "/etc/quantum/certs/ca.crt"]
  quantum1:
    container_name: quantum1
    build:
      context: "."
    extra_hosts:
      - "etcd.quantum.dev:172.18.0.4"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - $GOPATH/bin/quantum:/bin/quantum
      - ./certs/:/etc/quantum/certs/:ro
      - quantum1:/var/lib/quantum
    environment:
      QUANTUM_ENDPOINTS: "etcd.quantum.dev:2379"
      QUANTUM_PUBLIC_IP: "172.18.0.3"
      QUANTUM_TLS_CA_CERT: "/etc/quantum/certs/ca.crt"
      QUANTUM_TLS_CERT: "/etc/quantum/certs/quantum1.quantum.dev.crt"
      QUANTUM_TLS_KEY: "/etc/quantum/certs/quantum1.quantum.dev.key"
    networks:
      perf_net:
        ipv4_address: 172.18.0.3
    entrypoint: ["/bin/quantum"]
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd
    extra_hosts:
      - "etcd.quantum.dev:172.18.0.4"
    volumes:
      - etcd:/var/lib/etcd
      - ./certs/:/etc/quantum/certs/:ro
    networks:
      perf_net:
        ipv4_address: 172.18.0.4
    environment:
      ETCD_LISTEN_CLIENT_URLS: "https://etcd.quantum.dev:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "https://etcd.quantum.dev:2379"
      ETCD_CERT_FILE: "/etc/quantum/certs/etcd.quantum.dev.crt"
      ETCD_KEY_FILE: "/etc/quantum/certs/etcd.quantum.dev.key"
      ETCD_TRUSTED_CA_FILE: "/etc/quantum/certs/ca.crt"
      ETCD_DATA_DIR: "/var/lib/etcd"
      ETCD_NAME: "datastore"
    entrypoint: ["/usr/local/bin/etcd", "--client-cert-auth=true"]
networks:
  perf_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
volumes:
  etcd:
    driver: local
  quantum0:
    driver: local
  quantum1:
    driver: local
